// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDssQ_mV1vJFZMEB91DDogfnfXIU465rLk',
    appId: '1:289730161791:web:bd63a14e48ebd8102aa34a',
    messagingSenderId: '289730161791',
    projectId: 'banksampahfiks',
    authDomain: 'banksampahfiks.firebaseapp.com',
    storageBucket: 'banksampahfiks.firebasestorage.app',
    measurementId: 'G-TYY5YSVVL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwwDIIIPzIRsTdGxg0h7JCjDNxL_mBGCw',
    appId: '1:289730161791:android:27c59282021094152aa34a',
    messagingSenderId: '289730161791',
    projectId: 'banksampahfiks',
    storageBucket: 'banksampahfiks.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1i7_BRa3JQBJKiP7Rq70GIHvjczPuSyg',
    appId: '1:289730161791:ios:78749fc1f912e46c2aa34a',
    messagingSenderId: '289730161791',
    projectId: 'banksampahfiks',
    storageBucket: 'banksampahfiks.firebasestorage.app',
    iosBundleId: 'com.sampah.bankSampahFiks',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1i7_BRa3JQBJKiP7Rq70GIHvjczPuSyg',
    appId: '1:289730161791:ios:78749fc1f912e46c2aa34a',
    messagingSenderId: '289730161791',
    projectId: 'banksampahfiks',
    storageBucket: 'banksampahfiks.firebasestorage.app',
    iosBundleId: 'com.sampah.bankSampahFiks',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDssQ_mV1vJFZMEB91DDogfnfXIU465rLk',
    appId: '1:289730161791:web:7c3f5b9219d631a62aa34a',
    messagingSenderId: '289730161791',
    projectId: 'banksampahfiks',
    authDomain: 'banksampahfiks.firebaseapp.com',
    storageBucket: 'banksampahfiks.firebasestorage.app',
    measurementId: 'G-34CRMDHZ5Q',
  );
}
